using System.Collections.Generic;

namespace EmergencyPriority
{
    // Machine-translated UI strings (Options + panels). English is the source of truth; Get() returns the
    // locale string when present, else English. Community corrections welcome.
    public static class Translations
    {
        public static string Get(string key, string locale) =>
            (Loc.TryGetValue(locale, out var lm) && lm.TryGetValue(key, out var lv)) ? lv
            : (En.TryGetValue(key, out var v) ? v : key);

        public static readonly Dictionary<string, string> En = new Dictionary<string, string>
        {
            { "opt.Enabled.L", "Enable Emergency Priority" },
            { "opt.Enabled.D", "Keeps responding fire engines, ambulances and police cars alive and moving through traffic jams. Off = vanilla behaviour." },
            { "opt.DespawnGuard.L", "Prevent stuck responders from despawning" },
            { "opt.DespawnGuard.D", "Vanilla deletes a responding vehicle once it is flagged as stuck in traffic, and the emergency waits for a re-dispatch. With the guard, the vehicle looks for a new route instead." },
            { "opt.AutoReroute.L", "Re-route around congestion" },
            { "opt.AutoReroute.D", "Vanilla plans the route once, at dispatch. With this on, a responder that sits blocked in a jam requests a fresh route that accounts for current traffic." },
            { "opt.RerouteAfterSeconds.L", "Re-route after (seconds blocked)" },
            { "opt.RerouteAfterSeconds.D", "How long a responder must be continuously stuck behind traffic before it looks for a detour." },
            { "grp.Group", "Responding vehicles" },
            { "grp.GroupGeneral", "General" },
        };

        public static readonly Dictionary<string, Dictionary<string, string>> Loc = new Dictionary<string, Dictionary<string, string>>
        {
                ["de-DE"] = new Dictionary<string, string> { ["opt.Enabled.L"]="Emergency Priority aktivieren", ["opt.Enabled.D"]="Hält ausrückende Feuerwehr-, Rettungs- und Polizeifahrzeuge am Leben und in Bewegung durch Staus. Aus = Vanilla-Verhalten.", ["opt.DespawnGuard.L"]="Verhindert das Verschwinden festsitzender Einsatzfahrzeuge", ["opt.DespawnGuard.D"]="Vanilla löscht ein ausrückendes Fahrzeug, sobald es als im Stau festsitzend markiert wird, und der Einsatz wartet auf eine erneute Entsendung. Mit dem Schutz sucht das Fahrzeug stattdessen eine neue Route.", ["opt.AutoReroute.L"]="Um Staus herum umleiten", ["opt.AutoReroute.D"]="Vanilla plant die Route nur einmal, bei der Entsendung. Ist dies an, fordert ein Einsatzfahrzeug, das blockiert im Stau steht, eine neue Route an, die den aktuellen Verkehr berücksichtigt.", ["opt.RerouteAfterSeconds.L"]="Umleiten nach (Sekunden blockiert)", ["opt.RerouteAfterSeconds.D"]="Wie lange ein Einsatzfahrzeug ununterbrochen hinter dem Verkehr festsitzen muss, bevor es einen Umweg sucht.", ["grp.Group"]="Einsatzfahrzeuge", ["grp.GroupGeneral"]="Allgemein", },
                ["es-ES"] = new Dictionary<string, string> { ["opt.Enabled.L"]="Activar Emergency Priority", ["opt.Enabled.D"]="Mantiene con vida y en movimiento a los camiones de bomberos, ambulancias y coches de policía que acuden a una emergencia a través de los atascos. Desactivado = comportamiento vanilla.", ["opt.DespawnGuard.L"]="Evitar que los vehículos de emergencia atascados desaparezcan", ["opt.DespawnGuard.D"]="El vanilla elimina un vehículo que acude a una emergencia en cuanto se marca como atascado en el tráfico, y la emergencia espera a un nuevo despacho. Con esta protección, el vehículo busca una nueva ruta en su lugar.", ["opt.AutoReroute.L"]="Desviar para evitar la congestión", ["opt.AutoReroute.D"]="El vanilla planifica la ruta una sola vez, al despachar. Con esto activado, un vehículo que queda bloqueado en un atasco solicita una ruta nueva que tiene en cuenta el tráfico actual.", ["opt.RerouteAfterSeconds.L"]="Desviar tras (segundos bloqueado)", ["opt.RerouteAfterSeconds.D"]="Cuánto tiempo debe estar un vehículo de emergencia continuamente atascado detrás del tráfico antes de buscar un desvío.", ["grp.Group"]="Vehículos de emergencia", ["grp.GroupGeneral"]="General", },
                ["fr-FR"] = new Dictionary<string, string> { ["opt.Enabled.L"]="Activer Emergency Priority", ["opt.Enabled.D"]="Maintient en vie et en mouvement les camions de pompiers, ambulances et voitures de police en intervention à travers les embouteillages. Désactivé = comportement du jeu de base.", ["opt.DespawnGuard.L"]="Empêcher la disparition des véhicules d'intervention bloqués", ["opt.DespawnGuard.D"]="Le jeu de base supprime un véhicule en intervention dès qu'il est signalé comme bloqué dans le trafic, et l'urgence attend une nouvelle affectation. Avec la protection, le véhicule cherche plutôt un nouvel itinéraire.", ["opt.AutoReroute.L"]="Contourner les embouteillages", ["opt.AutoReroute.D"]="Le jeu de base planifie l'itinéraire une seule fois, à l'affectation. Avec cette option, un véhicule d'intervention bloqué dans un embouteillage demande un nouvel itinéraire tenant compte du trafic actuel.", ["opt.RerouteAfterSeconds.L"]="Recalculer l'itinéraire après (secondes bloqué)", ["opt.RerouteAfterSeconds.D"]="Combien de temps un véhicule d'intervention doit rester bloqué en continu derrière le trafic avant de chercher un détour.", ["grp.Group"]="Véhicules d'intervention", ["grp.GroupGeneral"]="Général", },
                ["it-IT"] = new Dictionary<string, string> { ["opt.Enabled.L"]="Abilita Emergency Priority", ["opt.Enabled.D"]="Mantiene attivi e in movimento tra il traffico i mezzi di soccorso in intervento: autopompe, ambulanze e volanti della polizia. Disattivato = comportamento originale.", ["opt.DespawnGuard.L"]="Impedisci la scomparsa dei soccorritori bloccati", ["opt.DespawnGuard.D"]="L'originale elimina un veicolo in intervento non appena viene contrassegnato come bloccato nel traffico, e l'emergenza attende un nuovo invio. Con la protezione, il veicolo cerca invece un nuovo percorso.", ["opt.AutoReroute.L"]="Devia intorno alla congestione", ["opt.AutoReroute.D"]="L'originale pianifica il percorso una sola volta, all'invio. Con questa opzione attiva, un soccorritore fermo bloccato in un ingorgo richiede un percorso aggiornato che tiene conto del traffico attuale.", ["opt.RerouteAfterSeconds.L"]="Devia dopo (secondi di blocco)", ["opt.RerouteAfterSeconds.D"]="Per quanto tempo un soccorritore deve restare continuativamente bloccato nel traffico prima di cercare una deviazione.", ["grp.Group"]="Veicoli in intervento", ["grp.GroupGeneral"]="Generale", },
                ["ja-JP"] = new Dictionary<string, string> { ["opt.Enabled.L"]="Emergency Priority を有効化", ["opt.Enabled.D"]="出動中の消防車、救急車、パトカーを渋滞の中でも消滅させず走行させ続けます。オフ = バニラの挙動。", ["opt.DespawnGuard.L"]="立ち往生した緊急車両の消滅を防止", ["opt.DespawnGuard.D"]="バニラでは、渋滞で立ち往生と判定された出動車両を削除し、緊急対応は再出動を待ちます。ガードを有効にすると、その車両は代わりに新しい経路を探します。", ["opt.AutoReroute.L"]="渋滞を迂回して再経路探索", ["opt.AutoReroute.D"]="バニラでは経路は出動時に一度だけ計画されます。これをオンにすると、渋滞で立ち往生した緊急車両が現在の交通状況を反映した新しい経路を要求します。", ["opt.RerouteAfterSeconds.L"]="再経路探索までの時間（立ち往生秒数）", ["opt.RerouteAfterSeconds.D"]="緊急車両が迂回路を探し始めるまでに、渋滞の後ろで連続して立ち往生している必要がある時間。", ["grp.Group"]="出動車両", ["grp.GroupGeneral"]="全般", },
                ["ko-KR"] = new Dictionary<string, string> { ["opt.Enabled.L"]="긴급 우선 통행 활성화", ["opt.Enabled.D"]="출동 중인 소방차, 구급차, 경찰차가 교통 정체를 뚫고 계속 이동하도록 유지합니다. 꺼짐 = 기본 게임 동작.", ["opt.DespawnGuard.L"]="정체된 출동 차량의 소멸 방지", ["opt.DespawnGuard.D"]="기본 게임은 출동 차량이 교통 정체에 갇힌 것으로 표시되면 이를 삭제하고, 긴급 상황은 재출동을 기다립니다. 이 보호 기능을 켜면 차량이 대신 새 경로를 찾습니다.", ["opt.AutoReroute.L"]="정체 우회 경로 재탐색", ["opt.AutoReroute.D"]="기본 게임은 출동 시 경로를 한 번만 계획합니다. 이 옵션을 켜면 정체에 막혀 멈춰 있는 출동 차량이 현재 교통 상황을 반영한 새 경로를 요청합니다.", ["opt.RerouteAfterSeconds.L"]="재탐색 시점 (막힌 지 초)", ["opt.RerouteAfterSeconds.D"]="출동 차량이 우회로를 찾기 전에 교통에 막혀 연속으로 정체되어야 하는 시간입니다.", ["grp.Group"]="출동 차량", ["grp.GroupGeneral"]="일반", },
                ["pl-PL"] = new Dictionary<string, string> { ["opt.Enabled.L"]="Włącz Emergency Priority", ["opt.Enabled.D"]="Utrzymuje interweniujące wozy strażackie, karetki i radiowozy przy życiu i w ruchu przez korki. Wyłączone = zachowanie z gry podstawowej.", ["opt.DespawnGuard.L"]="Zapobiegaj znikaniu utkniętych pojazdów ratowniczych", ["opt.DespawnGuard.D"]="Gra podstawowa usuwa interweniujący pojazd, gdy zostaje oznaczony jako utknięty w korku, a wezwanie czeka na ponowne wysłanie. Z tą ochroną pojazd zamiast tego szuka nowej trasy.", ["opt.AutoReroute.L"]="Zmiana trasy w celu ominięcia zatorów", ["opt.AutoReroute.D"]="Gra podstawowa planuje trasę tylko raz, przy wysłaniu. Gdy ta opcja jest włączona, pojazd ratowniczy stojący zablokowany w korku żąda nowej trasy uwzględniającej bieżący ruch.", ["opt.RerouteAfterSeconds.L"]="Zmiana trasy po (sekundach blokady)", ["opt.RerouteAfterSeconds.D"]="Jak długo pojazd ratowniczy musi być nieprzerwanie zablokowany w ruchu, zanim zacznie szukać objazdu.", ["grp.Group"]="Pojazdy interweniujące", ["grp.GroupGeneral"]="Ogólne", },
                ["pt-BR"] = new Dictionary<string, string> { ["opt.Enabled.L"]="Ativar Emergency Priority", ["opt.Enabled.D"]="Mantém caminhões de bombeiros, ambulâncias e viaturas policiais em atendimento vivos e em movimento no meio dos congestionamentos. Desativado = comportamento original.", ["opt.DespawnGuard.L"]="Impedir que veículos presos desapareçam", ["opt.DespawnGuard.D"]="O jogo original exclui um veículo em atendimento assim que ele é marcado como preso no trânsito, e a emergência aguarda um novo despacho. Com a proteção, o veículo procura uma nova rota em vez disso.", ["opt.AutoReroute.L"]="Recalcular rota contornando o congestionamento", ["opt.AutoReroute.D"]="O jogo original planeja a rota uma única vez, no despacho. Com isto ativado, um veículo que fica bloqueado em um congestionamento solicita uma rota nova que leva em conta o trânsito atual.", ["opt.RerouteAfterSeconds.L"]="Recalcular rota após (segundos bloqueado)", ["opt.RerouteAfterSeconds.D"]="Por quanto tempo um veículo precisa ficar continuamente preso atrás do trânsito antes de procurar um desvio.", ["grp.Group"]="Veículos em atendimento", ["grp.GroupGeneral"]="Geral", },
                ["ru-RU"] = new Dictionary<string, string> { ["opt.Enabled.L"]="Включить Emergency Priority", ["opt.Enabled.D"]="Помогает выезжающим пожарным машинам, каретам скорой помощи и полицейским машинам не застревать и двигаться сквозь пробки. Выкл = поведение оригинала.", ["opt.DespawnGuard.L"]="Не давать застрявшим экстренным машинам исчезать", ["opt.DespawnGuard.D"]="Оригинал удаляет выехавшую машину, как только она помечена застрявшей в пробке, и экстренная служба ждёт повторной отправки. С этой защитой машина вместо этого ищет новый маршрут.", ["opt.AutoReroute.L"]="Объезд заторов", ["opt.AutoReroute.D"]="Оригинал прокладывает маршрут один раз, при отправке. С включённым параметром машина, застрявшая в пробке, запрашивает новый маршрут с учётом текущего трафика.", ["opt.RerouteAfterSeconds.L"]="Перепрокладка через (секунд в заторе)", ["opt.RerouteAfterSeconds.D"]="Сколько времени машина должна непрерывно стоять в пробке, прежде чем начнёт искать объезд.", ["grp.Group"]="Выезжающие машины", ["grp.GroupGeneral"]="Общие", },
                ["zh-HANS"] = new Dictionary<string, string> { ["opt.Enabled.L"]="启用紧急优先", ["opt.Enabled.D"]="让正在出勤的消防车、救护车和警车得以在交通拥堵中存活并继续行进。关闭 = 原版行为。", ["opt.DespawnGuard.L"]="防止受困出勤车辆消失", ["opt.DespawnGuard.D"]="原版会在出勤车辆被标记为受困于交通时将其删除，紧急任务则等待重新派遣。启用此保护后，车辆会转而寻找新路线。", ["opt.AutoReroute.L"]="绕开拥堵重新规划路线", ["opt.AutoReroute.D"]="原版只在派遣时规划一次路线。开启此项后，堵在拥堵中的出勤车辆会请求一条考虑当前交通状况的新路线。", ["opt.RerouteAfterSeconds.L"]="多少秒后重新规划路线（受阻秒数）", ["opt.RerouteAfterSeconds.D"]="出勤车辆必须连续受阻于交通多久后才会寻找绕行路线。", ["grp.Group"]="出勤车辆", ["grp.GroupGeneral"]="常规", },
                ["zh-HANT"] = new Dictionary<string, string> { ["opt.Enabled.L"]="啟用緊急優先", ["opt.Enabled.D"]="讓出勤中的消防車、救護車與警車在塞車中維持存在並持續移動。關閉＝原版行為。", ["opt.DespawnGuard.L"]="防止受困的出勤車輛消失", ["opt.DespawnGuard.D"]="原版在出勤車輛被標記為卡在車陣中後便將其刪除，緊急事件則等待重新派遣。啟用防護後，車輛會改為尋找新路線。", ["opt.AutoReroute.L"]="繞過壅塞重新規劃路線", ["opt.AutoReroute.D"]="原版只在派遣當下規劃一次路線。啟用後，卡在車陣中動彈不得的出勤車輛會請求一條考量當前交通狀況的新路線。", ["opt.RerouteAfterSeconds.L"]="重新規劃路線前等待（受阻秒數）", ["opt.RerouteAfterSeconds.D"]="出勤車輛在尋找繞道前，必須連續卡在車陣後方多久。", ["grp.Group"]="出勤車輛", ["grp.GroupGeneral"]="一般", },
        };
    }
}
